# Default config for yam-cat

# *** Default camera names *** #
camera-names:
  "40120421": left
  "40120422": right
  "40120423": front
  "40120424": back

# *** Supported Video Formats *** #
# !! WIP, NOT USED !!
# You may edit this to enable different video formats in the GUI

# Format:
# fourcc: container
  # Description:
  # fourcc:
    # used by OpenCV VideoWriter
  # container:
    # file extension

video-formats:
  h264: mp4
  raw: avi

# *** Default Arduino hardware settings *** #
arduino:
  address: /dev/ttyACM0
  pin: 9

# *** Default Camera Trigger Lines *** #

# Format:
# GUID: trigger-line

# Example:
# 2676016BC31A: 4

# tiscams don't have a specific trigger line, so just set as 0
camera-serials:
  23839514: 4
  40092194: 2
  "40120421": 0
  "40120422": 0
  "40120423": 0
  "40120424": 0

# tiscams don't have a specific trigger line, so just set as 0
camera-guids:
  2676016BC31A: 4
  267601CA59E7: 2
  "40120421": 0
  "40120422": 0
  "40120423": 0
  "40120424": 0
