# Config for yam-cat GUI

# *** Default Camera Trigger Lines *** #

# Format:
# GUID: trigger-line

# Example:
# 2676016BC31A: 4

camera-serials:
  23839514: 4
  40092194: 2

camera-guids:
  2676016BC31A: 4
  267601CA59E7: 2


# *** Video Formats *** #
# You may edit this to enable different video formats in the GUI

# Format:
# fourcc: container
  # Description:
  # fourcc:
    # used by OpenCV VideoWriter
  # container:
    # file extension

video-formats:
  mp4v: avi

# Default Arduino hardware settings
arduino:
  address: /dev/ttyACM0
  pin: 9
