# Config for yam-cat GUI

# *** Default Camera Trigger Lines *** #

# Format:
# GUID: trigger-line

# Example:
# 2676016BC31A: 4

camera_guids:
  2676016BC31A: 4
  267601CA59E7: 2


# *** Video Formats *** #
# You may edit this to enable differnt video formats in the GUI

# Format:
# fourcc: container

# Description:
# fourcc: used by OpenCV VideoWriter
# container: file extension

# Example:
# mp4v: avi

mp4v: avi
